language: objective-c
os: osx
osx_image: xcode10

env:
  global:
    - XCODE_WORKSPACE=OC-YL/OC-YL.xcworkspace 
  matrix:
    - SCHEME="OC-YL"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod install 
script:
  - xcodebuild -workspace "OC-YL.xcworkspace " -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - xcodebuild -workspace "OC-YL.xcworkspace " -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - pod lib lint --allow-warnings
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 10
